"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AUTO_REDACT_CONTROLS = exports.NUMERIC_CONTROL_TYPES = exports.RESERVED_FIELD_NAMES = exports.MIN_VERSION_STAMP_LENGTH = exports.versionStamp = exports.VERSION_SUFFIX_RAND_LEN = exports.OBJ_ID_SEP = exports.DEFAULT_ALTERNATE_ID_FIELDS = exports.DEFAULT_MIN_WRITES = exports.DEFAULT_MAX_VERSIONS = void 0;
const util_js_1 = require("./util.js");
exports.DEFAULT_MAX_VERSIONS = 5;
exports.DEFAULT_MIN_WRITES = 0;
exports.DEFAULT_ALTERNATE_ID_FIELDS = ["name", "username", "email"];
exports.OBJ_ID_SEP = "_MORM_";
exports.VERSION_SUFFIX_RAND_LEN = 16;
const versionStamp = () => `_${Date.now()}_${(0, util_js_1.rand)(exports.VERSION_SUFFIX_RAND_LEN)}`;
exports.versionStamp = versionStamp;
exports.MIN_VERSION_STAMP_LENGTH = (0, exports.versionStamp)().length;
exports.RESERVED_FIELD_NAMES = ["redaction", "removed"];
exports.NUMERIC_CONTROL_TYPES = ["duration", "timestamp", "range"];
exports.AUTO_REDACT_CONTROLS = ["password", "hidden", "system"];
