"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.AUTO_REDACT_CONTROLS = exports.NUMERIC_CONTROL_TYPES = exports.RESERVED_FIELD_NAMES = exports.OBJ_ID_SEP = exports.VERSION_PREFIX = exports.DEFAULT_ALTERNATE_ID_FIELDS = exports.DEFAULT_MIN_WRITES = exports.DEFAULT_MAX_VERSIONS = void 0;
exports.DEFAULT_MAX_VERSIONS = 5;
exports.DEFAULT_MIN_WRITES = 0;
exports.DEFAULT_ALTERNATE_ID_FIELDS = ["name", "username", "email"];
exports.VERSION_PREFIX = "v_";
exports.OBJ_ID_SEP = "_MORM_";
exports.RESERVED_FIELD_NAMES = ["redaction", "removed"];
exports.NUMERIC_CONTROL_TYPES = ["duration", "timestamp", "range"];
exports.AUTO_REDACT_CONTROLS = ["password", "hidden", "system"];
