export const DEFAULT_MAX_VERSIONS = 5;
export const DEFAULT_MIN_WRITES = 0;
export const DEFAULT_ALTERNATE_ID_FIELDS = ["name", "username", "email"];
export const VERSION_PREFIX = "v_";
export const RESERVED_FIELD_NAMES = ["redaction", "removed"];
export const NUMERIC_CONTROL_TYPES = ["duration", "timestamp", "range"];
export const AUTO_REDACT_CONTROLS = ["password", "hidden", "system"];
export const DEFAULT_FIELD_INDEX_LEVELS = 1;
export const DEFAULT_ID_INDEX_LEVELS = 1;
